#!/bin/bash
for modtype in dis hyb; do
    for process in b bb nb p; do
	for observation in nb p; do
	    for seed in {1..100}; do
		for iterations in 4000 10000 20000; do
		    sqsub --mpp=1G -r 7d -q serial -o fit.$modtype.$process.$observation.$seed.$iterations.rout make fit.$modtype.$process.$observation.$seed.$iterations.Rout
       		done	
	    done
        done
    done
 done
