#!/bin/bash
for modtype in hyb; do
    for process in b bb p nb; do
    for observation in nb p; do
        for seed in {1..100}; do
	    for iterations in 4000; do
	    	    make fit.$modtype.$process.$observation.$seed.$iterations.Rout
       		    	 done	
			     done
        done
    done
 done
