#!/bin/bash
for modtype in dis hyb; do
    for process in b bb nb p; do
	for observation in nb p; do
	    for ((seed=1;i<1000;seed++)); do
		for iterations in 4000 10000 20000; do
		    make fit.$modtype.$process.$observation.$seed.$iterations.Rout
       		done	
	    done
        done
    done
 done
